/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compomics.deep_lc_gui.view;

import java.io.File;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 * The GUI main frame.
 *
 * @author Niels Hulstaert
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Prediction peptides file chooser.
     */
    private final JFileChooser predictionPeptidesChooser = new JFileChooser();
    /**
     * Calibration peptides chooser.
     */
    private final JFileChooser calibrationPeptidesChooser = new JFileChooser();
    /**
     * Output file chooser.
     */
    private final JFileChooser outputFileChooser = new JFileChooser();
    /**
     * Model file chooser.
     */
    private final JFileChooser modelFileChooser = new JFileChooser();

    /**
     * No-arg constructor.
     */
    public MainFrame() {
        initComponents();
    }

    public JFileChooser getPredictionPeptidesChooser() {
        return predictionPeptidesChooser;
    }

    public JFileChooser getCalibrationPeptidesChooser() {
        return calibrationPeptidesChooser;
    }

    public JFileChooser getOutputFileChooser() {
        return outputFileChooser;
    }

    public JFileChooser getModelFileChooser() {
        return modelFileChooser;
    }

    public JButton getCalibrationPeptidesButton() {
        return calibrationPeptidesButton;
    }

    public JTextField getCalibrationPeptidesTextField() {
        return calibrationPeptidesTextField;
    }

    public JButton getModelButton() {
        return modelButton;
    }

    public JList<File> getModelList() {
        return modelList;
    }

    public JTextField getNumberOfThreadsTextField() {
        return numberOfThreadsTextField;
    }

    public JButton getOutputFileButton() {
        return outputFileButton;
    }

    public JTextField getOutputFileTextField() {
        return outputFileTextField;
    }

    public JButton getPredictionPeptidesButton() {
        return predictionPeptidesButton;
    }

    public JTextField getPredictionPeptidesTextField() {
        return predictionPeptidesTextField;
    }

    public JButton getRemoveModelButton() {
        return removeModelButton;
    }

    public JTextField getSplitCalibrationTextField() {
        return splitCalibrationTextField;
    }        
  
    public JButton getCancelButton() {
        return cancelButton;
    }
    
    public JButton getStartButton() {
        return startButton;
    }

    public JPanel getTopPanel() {
        return topPanel;
    }

    public JLabel getInfoLabel() {
        return infoLabel;
    } 

    public JTextArea getLogTextArea() {
        return logTextArea;
    }

//    public Console getConsole() {
//        return console;
//    }        

    public JButton getClearButton() {
        return clearButton;
    }  

    public JTextField getDictionaryDividerTextField() {
        return DictionaryDividerTextField;
    }   

    public JTextField getBatchNumberTextField() {
        return batchNumberTextField;
    }        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parentPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        firstPanel = new javax.swing.JPanel();
        predictionPeptidesLabel = new javax.swing.JLabel();
        calibrationPeptidesLabel = new javax.swing.JLabel();
        outputFileLabel = new javax.swing.JLabel();
        calibrationPeptidesTextField = new javax.swing.JTextField();
        calibrationPeptidesButton = new javax.swing.JButton();
        predictionPeptidesTextField = new javax.swing.JTextField();
        predictionPeptidesButton = new javax.swing.JButton();
        outputFileTextField = new javax.swing.JTextField();
        outputFileButton = new javax.swing.JButton();
        modelLabel = new javax.swing.JLabel();
        numberOfThreadsLabel = new javax.swing.JLabel();
        splitCalibrationTextField = new javax.swing.JTextField();
        splitCalibrationLabel = new javax.swing.JLabel();
        numberOfThreadsTextField = new javax.swing.JTextField();
        dictionaryDividerLabel = new javax.swing.JLabel();
        DictionaryDividerTextField = new javax.swing.JTextField();
        modelScrollPane1 = new javax.swing.JScrollPane();
        modelList = new javax.swing.JList<>();
        modelButton = new javax.swing.JButton();
        removeModelButton = new javax.swing.JButton();
        batchNumberLabel = new javax.swing.JLabel();
        batchNumberTextField = new javax.swing.JTextField();
        lastPanel = new javax.swing.JPanel();
        clearButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        bottomPanel = new javax.swing.JPanel();
        infoLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        parentPanel.setBackground(new java.awt.Color(255, 255, 255));

        topPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        topPanel.setOpaque(false);
        topPanel.setLayout(new java.awt.CardLayout());

        firstPanel.setName("firstPanel"); // NOI18N
        firstPanel.setOpaque(false);

        predictionPeptidesLabel.setText("Peptides to make predictions for (peprec format):");

        calibrationPeptidesLabel.setText("Peptide (e.g. observed on yout setup or iRT) for calibration:");

        outputFileLabel.setText("Choose an output file:");

        calibrationPeptidesTextField.setEnabled(false);

        calibrationPeptidesButton.setText("choose");
        calibrationPeptidesButton.setToolTipText("Select a directory for the moFF output");
        calibrationPeptidesButton.setMaximumSize(new java.awt.Dimension(80, 25));
        calibrationPeptidesButton.setMinimumSize(new java.awt.Dimension(80, 25));
        calibrationPeptidesButton.setPreferredSize(new java.awt.Dimension(80, 25));

        predictionPeptidesTextField.setEnabled(false);

        predictionPeptidesButton.setText("choose");
        predictionPeptidesButton.setToolTipText("Choose the PeptideShaker directory location\n");
        predictionPeptidesButton.setMaximumSize(new java.awt.Dimension(80, 25));
        predictionPeptidesButton.setMinimumSize(new java.awt.Dimension(80, 25));
        predictionPeptidesButton.setPreferredSize(new java.awt.Dimension(80, 25));

        outputFileTextField.setEnabled(false);

        outputFileButton.setText("choose");
        outputFileButton.setToolTipText("Select a directory for the moFF output");
        outputFileButton.setMaximumSize(new java.awt.Dimension(80, 25));
        outputFileButton.setMinimumSize(new java.awt.Dimension(80, 25));
        outputFileButton.setPreferredSize(new java.awt.Dimension(80, 25));

        modelLabel.setText("Choose model:");

        numberOfThreadsLabel.setText("Number of threads:");

        splitCalibrationLabel.setText("Split calibration:");

        dictionaryDividerLabel.setText("Dictionary divider:");

        modelScrollPane1.setViewportView(modelList);

        modelButton.setText("choose");
        modelButton.setToolTipText("Select a directory for the moFF output");
        modelButton.setMaximumSize(new java.awt.Dimension(80, 25));
        modelButton.setMinimumSize(new java.awt.Dimension(80, 25));
        modelButton.setPreferredSize(new java.awt.Dimension(80, 25));

        removeModelButton.setText("remove");
        removeModelButton.setToolTipText("Select a directory for the moFF output");
        removeModelButton.setMaximumSize(new java.awt.Dimension(80, 25));
        removeModelButton.setMinimumSize(new java.awt.Dimension(80, 25));
        removeModelButton.setPreferredSize(new java.awt.Dimension(80, 25));

        batchNumberLabel.setText("Batch number:");

        javax.swing.GroupLayout firstPanelLayout = new javax.swing.GroupLayout(firstPanel);
        firstPanel.setLayout(firstPanelLayout);
        firstPanelLayout.setHorizontalGroup(
            firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstPanelLayout.createSequentialGroup()
                .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(predictionPeptidesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(calibrationPeptidesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(185, 185, 185))
            .addGroup(firstPanelLayout.createSequentialGroup()
                .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(outputFileLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modelLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(110, 110, 110)
                .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(modelScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(predictionPeptidesTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calibrationPeptidesTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputFileTextField)
                    .addGroup(firstPanelLayout.createSequentialGroup()
                        .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(splitCalibrationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dictionaryDividerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DictionaryDividerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(splitCalibrationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(batchNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numberOfThreadsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberOfThreadsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(batchNumberTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calibrationPeptidesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(predictionPeptidesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outputFileButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(modelButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(removeModelButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        firstPanelLayout.setVerticalGroup(
            firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstPanelLayout.createSequentialGroup()
                .addComponent(predictionPeptidesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(predictionPeptidesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(predictionPeptidesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(calibrationPeptidesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calibrationPeptidesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calibrationPeptidesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputFileLabel))
                .addGap(18, 18, 18)
                .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstPanelLayout.createSequentialGroup()
                        .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modelLabel)
                            .addComponent(modelScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberOfThreadsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dictionaryDividerLabel)
                                .addComponent(DictionaryDividerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(numberOfThreadsLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(splitCalibrationLabel)
                            .addComponent(splitCalibrationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(batchNumberLabel)
                            .addComponent(batchNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addGroup(firstPanelLayout.createSequentialGroup()
                        .addComponent(modelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeModelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        topPanel.add(firstPanel, "firstPanel");

        lastPanel.setName("lastPanel"); // NOI18N
        lastPanel.setOpaque(false);

        clearButton.setText("clear");
        clearButton.setMaximumSize(new java.awt.Dimension(80, 25));
        clearButton.setMinimumSize(new java.awt.Dimension(80, 25));
        clearButton.setPreferredSize(new java.awt.Dimension(80, 25));

        logTextArea.setColumns(20);
        logTextArea.setRows(5);
        jScrollPane2.setViewportView(logTextArea);

        javax.swing.GroupLayout lastPanelLayout = new javax.swing.GroupLayout(lastPanel);
        lastPanel.setLayout(lastPanelLayout);
        lastPanelLayout.setHorizontalGroup(
            lastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lastPanelLayout.createSequentialGroup()
                .addGap(0, 788, Short.MAX_VALUE)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane2)
        );
        lastPanelLayout.setVerticalGroup(
            lastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lastPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        topPanel.add(lastPanel, "lastPanel");

        bottomPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        bottomPanel.setOpaque(false);

        infoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        infoLabel.setMaximumSize(new java.awt.Dimension(34, 20));
        infoLabel.setMinimumSize(new java.awt.Dimension(34, 20));
        infoLabel.setName(""); // NOI18N
        infoLabel.setPreferredSize(new java.awt.Dimension(34, 20));

        startButton.setText("start");
        startButton.setMaximumSize(new java.awt.Dimension(80, 25));
        startButton.setMinimumSize(new java.awt.Dimension(80, 25));
        startButton.setPreferredSize(new java.awt.Dimension(80, 25));
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("cancel");
        cancelButton.setPreferredSize(new java.awt.Dimension(80, 25));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(infoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(203, 203, 203)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout parentPanelLayout = new javax.swing.GroupLayout(parentPanel);
        parentPanel.setLayout(parentPanelLayout);
        parentPanelLayout.setHorizontalGroup(
            parentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(parentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        parentPanelLayout.setVerticalGroup(
            parentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(parentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(parentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DictionaryDividerTextField;
    private javax.swing.JLabel batchNumberLabel;
    private javax.swing.JTextField batchNumberTextField;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton calibrationPeptidesButton;
    private javax.swing.JLabel calibrationPeptidesLabel;
    private javax.swing.JTextField calibrationPeptidesTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel dictionaryDividerLabel;
    private javax.swing.JPanel firstPanel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel lastPanel;
    private javax.swing.JTextArea logTextArea;
    private javax.swing.JButton modelButton;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JList<File> modelList;
    private javax.swing.JScrollPane modelScrollPane1;
    private javax.swing.JLabel numberOfThreadsLabel;
    private javax.swing.JTextField numberOfThreadsTextField;
    private javax.swing.JButton outputFileButton;
    private javax.swing.JLabel outputFileLabel;
    private javax.swing.JTextField outputFileTextField;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JButton predictionPeptidesButton;
    private javax.swing.JLabel predictionPeptidesLabel;
    private javax.swing.JTextField predictionPeptidesTextField;
    private javax.swing.JButton removeModelButton;
    private javax.swing.JLabel splitCalibrationLabel;
    private javax.swing.JTextField splitCalibrationTextField;
    private javax.swing.JButton startButton;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
